"""
Generate synthetic onboarding personas for Vidya V3 roadmap testing.

This script writes deterministic, realistic onboarding inputs to:
synthetic_test_data/onboarding_inputs/user_XXX.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_OUTPUT_DIR = BASE_DIR / "synthetic_test_data" / "onboarding_inputs"


PERSONAS: list[dict[str, Any]] = [
    {
        "full_name": "Aarav Menon",
        "age": 29,
        "location": "Bengaluru",
        "education": "B.Tech in Information Technology",
        "current_role": "Backend Engineer",
        "years_experience": 6,
        "current_salary_monthly": 145000,
        "target_role": "Senior Backend Engineer",
        "target_salary_monthly": 230000,
        "primary_goal": "Move into a senior backend role by improving system design, distributed systems, and cloud architecture depth.",
        "skill_gaps": ["distributed system design", "Kafka architecture", "AWS deployment patterns", "technical design documentation"],
        "known_skills": ["Java", "Spring Boot", "REST APIs", "PostgreSQL", "Redis"],
        "learning_style": "structured",
        "weekly_hours_available": 7,
        "device_access": "laptop",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants to own larger engineering decisions instead of only executing tickets assigned by senior architects.",
        "biggest_fear": "He worries that weak system design depth will block him in senior engineering interviews.",
        "icp_type": "high",
    },
    {
        "full_name": "Neha Kulkarni",
        "age": 31,
        "location": "Pune",
        "education": "MCA",
        "current_role": "Data Analyst",
        "years_experience": 7,
        "current_salary_monthly": 118000,
        "target_role": "Data Scientist",
        "target_salary_monthly": 210000,
        "primary_goal": "Transition from dashboard reporting into data science work involving forecasting, experimentation, and machine learning.",
        "skill_gaps": ["machine learning algorithms", "model evaluation", "feature engineering", "Python production workflows"],
        "known_skills": ["SQL", "Power BI", "Excel", "basic Python", "business analytics"],
        "learning_style": "hands-on",
        "weekly_hours_available": 8,
        "device_access": "both",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "medium",
        "motivation": "She has strong business intuition and wants her work to influence product decisions, not just monthly reports.",
        "biggest_fear": "She fears being labelled as only a reporting analyst while machine learning roles move further away.",
        "icp_type": "high",
    },
    {
        "full_name": "Rohan Bhatia",
        "age": 27,
        "location": "Gurugram",
        "education": "B.Tech in Electronics and Communication",
        "current_role": "Cloud Support Engineer",
        "years_experience": 4,
        "current_salary_monthly": 92000,
        "target_role": "Cloud Solutions Architect",
        "target_salary_monthly": 180000,
        "primary_goal": "Move from support-heavy cloud work into architecture and implementation roles involving AWS, Kubernetes, and scalable infrastructure.",
        "skill_gaps": ["Kubernetes architecture", "Terraform", "cloud cost optimization", "enterprise solution design"],
        "known_skills": ["AWS basics", "Linux", "incident management", "networking fundamentals", "Bash scripting"],
        "learning_style": "practice",
        "weekly_hours_available": 6,
        "device_access": "laptop",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants to stop working night shifts and convert his cloud exposure into higher-impact engineering work.",
        "biggest_fear": "He fears being stuck in reactive support roles while peers move into DevOps and architecture positions.",
        "icp_type": "high",
    },
    {
        "full_name": "Ishita Sengupta",
        "age": 34,
        "location": "Hyderabad",
        "education": "B.E. in Computer Science",
        "current_role": "Engineering Manager",
        "years_experience": 10,
        "current_salary_monthly": 245000,
        "target_role": "Director of Engineering",
        "target_salary_monthly": 360000,
        "primary_goal": "Strengthen leadership, execution planning, and technical strategy skills required for a Director of Engineering role.",
        "skill_gaps": ["engineering strategy", "executive communication", "multi-team planning", "metrics-driven delivery"],
        "known_skills": ["people management", "JavaScript", "microservices", "agile delivery", "hiring"],
        "learning_style": "visual",
        "weekly_hours_available": 5,
        "device_access": "both",
        "language_preference": "en",
        "confidence_level": "high",
        "urgency": "medium",
        "motivation": "She wants to influence product and business direction instead of only managing sprint execution.",
        "biggest_fear": "She worries that senior leadership may see her as operational rather than strategic.",
        "icp_type": "high",
    },
    {
        "full_name": "Karan Malhotra",
        "age": 28,
        "location": "Noida",
        "education": "B.Tech in Mechanical Engineering",
        "current_role": "QA Automation Engineer",
        "years_experience": 5,
        "current_salary_monthly": 87000,
        "target_role": "SDET Lead",
        "target_salary_monthly": 165000,
        "primary_goal": "Grow from automation scripting into a lead SDET role with stronger framework design, CI/CD, and backend testing capability.",
        "skill_gaps": ["test framework architecture", "API contract testing", "CI/CD pipeline integration", "performance testing basics"],
        "known_skills": ["Selenium", "Java", "manual testing", "Postman", "Jenkins basics"],
        "learning_style": "hands-on",
        "weekly_hours_available": 9,
        "device_access": "laptop",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants QA to be treated as engineering work and not as the final checklist before release.",
        "biggest_fear": "He fears automation work becoming repetitive if he does not learn architecture and backend testing deeply.",
        "icp_type": "high",
    },
    {
        "full_name": "Meera Nair",
        "age": 30,
        "location": "Chennai",
        "education": "B.Sc in Statistics and MBA in Analytics",
        "current_role": "Product Analyst",
        "years_experience": 6,
        "current_salary_monthly": 132000,
        "target_role": "AI Product Manager",
        "target_salary_monthly": 240000,
        "primary_goal": "Move into AI product management by learning model capabilities, experimentation, prompt workflows, and AI feature evaluation.",
        "skill_gaps": ["AI product strategy", "LLM evaluation", "prompt engineering", "technical communication with ML teams"],
        "known_skills": ["product analytics", "SQL", "A/B testing", "user research", "Mixpanel"],
        "learning_style": "video-first",
        "weekly_hours_available": 6,
        "device_access": "both",
        "language_preference": "en",
        "confidence_level": "low",
        "urgency": "medium",
        "motivation": "She wants to be part of AI product building early and not remain limited to post-launch analytics.",
        "biggest_fear": "She fears technical PMs with engineering backgrounds will be preferred unless she develops enough AI fluency.",
        "icp_type": "high",
    },
    {
        "full_name": "Siddharth Rao",
        "age": 26,
        "location": "Mumbai",
        "education": "B.Tech in Computer Engineering",
        "current_role": "Frontend Developer",
        "years_experience": 3,
        "current_salary_monthly": 76000,
        "target_role": "Full Stack Engineer",
        "target_salary_monthly": 145000,
        "primary_goal": "Become a full stack engineer by learning backend APIs, database design, authentication, and deployment workflows.",
        "skill_gaps": ["Node.js backend development", "database schema design", "authentication and authorization", "Docker deployment"],
        "known_skills": ["React", "TypeScript", "HTML", "CSS", "Redux"],
        "learning_style": "practice",
        "weekly_hours_available": 10,
        "device_access": "laptop",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants to stop being dependent on backend teammates and qualify for better product company roles.",
        "biggest_fear": "He worries that frontend-only salary growth will slow without backend ownership.",
        "icp_type": "high",
    },
    {
        "full_name": "Priyanka Joshi",
        "age": 32,
        "location": "Ahmedabad",
        "education": "B.E. in Information Technology",
        "current_role": "Business Intelligence Developer",
        "years_experience": 8,
        "current_salary_monthly": 110000,
        "target_role": "Analytics Engineering Lead",
        "target_salary_monthly": 200000,
        "primary_goal": "Shift into analytics engineering leadership by learning modern data stacks, dbt, data modelling, and stakeholder planning.",
        "skill_gaps": ["dbt", "data warehouse modelling", "Airflow orchestration", "analytics engineering best practices"],
        "known_skills": ["SQL", "Tableau", "Snowflake basics", "dashboard design", "requirements gathering"],
        "learning_style": "structured",
        "weekly_hours_available": 5,
        "device_access": "both",
        "language_preference": "en",
        "confidence_level": "high",
        "urgency": "medium",
        "motivation": "She wants years of BI experience to translate into a modern data role instead of legacy reporting work.",
        "biggest_fear": "She fears being replaced by younger candidates who already know tools like dbt and Airflow.",
        "icp_type": "high",
    },
    {
        "full_name": "Aditya Iyer",
        "age": 25,
        "location": "Bengaluru",
        "education": "B.Tech in Computer Science",
        "current_role": "Software Engineer",
        "years_experience": 2,
        "current_salary_monthly": 68000,
        "target_role": "AI Application Engineer",
        "target_salary_monthly": 150000,
        "primary_goal": "Build AI-powered applications using LLM APIs, vector databases, RAG pipelines, and production-ready backend services.",
        "skill_gaps": ["LLM application design", "RAG architecture", "Pinecone retrieval concepts", "evaluation of AI responses"],
        "known_skills": ["Python", "FastAPI", "JavaScript", "MongoDB", "Git"],
        "learning_style": "hands-on",
        "weekly_hours_available": 12,
        "device_access": "laptop",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He is excited by AI tools and wants to build real applications instead of only watching tutorials.",
        "biggest_fear": "He fears missing the AI hiring wave because he has no strong portfolio projects to show recruiters.",
        "icp_type": "high",
    },
    {
        "full_name": "Tanvi Deshpande",
        "age": 33,
        "location": "Nagpur",
        "education": "B.Tech in Electronics",
        "current_role": "Technical Program Manager",
        "years_experience": 9,
        "current_salary_monthly": 185000,
        "target_role": "Platform Program Lead",
        "target_salary_monthly": 280000,
        "primary_goal": "Lead complex platform programs by improving technical architecture understanding, roadmap planning, and cross-functional execution.",
        "skill_gaps": ["platform architecture fundamentals", "roadmap prioritization", "engineering dependency mapping", "data-driven program reporting"],
        "known_skills": ["program management", "Jira", "stakeholder communication", "release planning", "risk management"],
        "learning_style": "visual",
        "weekly_hours_available": 6,
        "device_access": "both",
        "language_preference": "en",
        "confidence_level": "medium",
        "urgency": "medium",
        "motivation": "She wants to be trusted in technical planning rooms and not just called in after decisions are already made.",
        "biggest_fear": "She fears that without stronger technical fluency, her career will plateau below senior platform leadership roles.",
        "icp_type": "high",
    },
    {
        "full_name": "Ritika Yadav",
        "age": 21,
        "location": "Gorakhpur",
        "education": "B.Sc in Mathematics, final year",
        "current_role": "Student",
        "years_experience": 0,
        "current_salary_monthly": 0,
        "target_role": "Junior Frontend Developer",
        "target_salary_monthly": 28000,
        "primary_goal": "Learn frontend development from the basics and become ready for entry-level web developer jobs after graduation.",
        "skill_gaps": ["HTML structure", "CSS layouts", "JavaScript fundamentals", "portfolio project building"],
        "known_skills": ["basic computer usage", "college-level mathematics", "MS Word", "basic internet research"],
        "learning_style": "video-first",
        "weekly_hours_available": 14,
        "device_access": "mobile",
        "language_preference": "hinglish",
        "confidence_level": "low",
        "urgency": "high",
        "motivation": "She wants to become financially independent before her younger brother starts college.",
        "biggest_fear": "She fears students from bigger cities with laptops and better English will always be ahead of her.",
        "icp_type": "low",
    },
    {
        "full_name": "Mohit Saini",
        "age": 23,
        "location": "Kota",
        "education": "B.Com graduate",
        "current_role": "Customer Support Executive",
        "years_experience": 1,
        "current_salary_monthly": 18000,
        "target_role": "Technical Support Associate",
        "target_salary_monthly": 32000,
        "primary_goal": "Move from general customer support into technical support by learning basic networking, troubleshooting, and ticket documentation.",
        "skill_gaps": ["networking basics", "SQL queries", "technical troubleshooting", "professional email writing"],
        "known_skills": ["customer handling", "Hindi communication", "CRM usage", "basic Excel"],
        "learning_style": "structured",
        "weekly_hours_available": 9,
        "device_access": "mobile",
        "language_preference": "hi",
        "confidence_level": "low",
        "urgency": "medium",
        "motivation": "He wants a stable job where salary can grow without depending on call targets and rotational shifts.",
        "biggest_fear": "He fears his commerce background will make recruiters reject him before he can explain his effort.",
        "icp_type": "low",
    },
    {
        "full_name": "Pooja Kumari",
        "age": 20,
        "location": "Dhanbad",
        "education": "Diploma in Computer Applications",
        "current_role": "Part-time Data Entry Operator",
        "years_experience": 1,
        "current_salary_monthly": 9000,
        "target_role": "Python Intern",
        "target_salary_monthly": 20000,
        "primary_goal": "Learn Python step by step and qualify for a paid internship that can help her enter the technology field.",
        "skill_gaps": ["Python syntax", "problem solving", "GitHub usage", "basic projects with files and APIs"],
        "known_skills": ["typing", "Excel", "basic Windows", "data entry accuracy"],
        "learning_style": "practice",
        "weekly_hours_available": 12,
        "device_access": "mobile",
        "language_preference": "hinglish",
        "confidence_level": "low",
        "urgency": "high",
        "motivation": "She wants to contribute to household expenses and show her family that a tech career is possible.",
        "biggest_fear": "She fears getting stuck in low-paid data entry because she does not know how to build coding confidence.",
        "icp_type": "low",
    },
    {
        "full_name": "Sameer Khan",
        "age": 24,
        "location": "Aligarh",
        "education": "B.A. in English",
        "current_role": "Unemployed Fresher",
        "years_experience": 0,
        "current_salary_monthly": 0,
        "target_role": "Digital Operations Associate",
        "target_salary_monthly": 25000,
        "primary_goal": "Become employable for digital operations roles by learning Excel, basic SQL, workflow tools, and workplace communication.",
        "skill_gaps": ["advanced Excel", "SQL basics", "process documentation", "job interview preparation"],
        "known_skills": ["English writing", "basic computer knowledge", "Google search", "MS PowerPoint"],
        "learning_style": "visual",
        "weekly_hours_available": 18,
        "device_access": "mobile",
        "language_preference": "hinglish",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants to start earning quickly because relatives have started questioning his degree and job prospects.",
        "biggest_fear": "He fears wasting more months applying randomly without understanding which skills employers expect.",
        "icp_type": "low",
    },
    {
        "full_name": "Anjali Verma",
        "age": 22,
        "location": "Gwalior",
        "education": "BCA, final semester",
        "current_role": "Student",
        "years_experience": 0,
        "current_salary_monthly": 0,
        "target_role": "Software Developer Trainee",
        "target_salary_monthly": 30000,
        "primary_goal": "Prepare for campus and off-campus software trainee roles by strengthening programming basics, DSA, and simple web projects.",
        "skill_gaps": ["data structures", "algorithmic thinking", "resume-worthy projects", "technical interview confidence"],
        "known_skills": ["C programming", "basic Java", "HTML", "college database concepts"],
        "learning_style": "structured",
        "weekly_hours_available": 16,
        "device_access": "both",
        "language_preference": "hinglish",
        "confidence_level": "low",
        "urgency": "high",
        "motivation": "She wants to be the first person in her family to get a private-sector tech job.",
        "biggest_fear": "She fears freezing during interviews even when she has studied the topic earlier.",
        "icp_type": "low",
    },
    {
        "full_name": "Harsh Patel",
        "age": 25,
        "location": "Rajkot",
        "education": "ITI in Electrical Trade",
        "current_role": "Mobile Repair Shop Assistant",
        "years_experience": 2,
        "current_salary_monthly": 16000,
        "target_role": "Web Developer Intern",
        "target_salary_monthly": 22000,
        "primary_goal": "Switch from repair shop work into web development by learning practical HTML, CSS, JavaScript, and small client websites.",
        "skill_gaps": ["responsive web design", "JavaScript events", "domain and hosting basics", "client project delivery"],
        "known_skills": ["mobile hardware troubleshooting", "customer handling", "basic Android usage", "YouTube-based self learning"],
        "learning_style": "hands-on",
        "weekly_hours_available": 10,
        "device_access": "mobile",
        "language_preference": "hi",
        "confidence_level": "medium",
        "urgency": "medium",
        "motivation": "He has seen small businesses in his city needing websites and wants a skill that can bring freelance income.",
        "biggest_fear": "He fears that without a formal engineering degree, people will not take his coding work seriously.",
        "icp_type": "low",
    },
    {
        "full_name": "Sneha Mishra",
        "age": 19,
        "location": "Muzaffarpur",
        "education": "B.A. first year",
        "current_role": "Student",
        "years_experience": 0,
        "current_salary_monthly": 0,
        "target_role": "UI Design Intern",
        "target_salary_monthly": 18000,
        "primary_goal": "Explore UI design and build a beginner portfolio using mobile-friendly tools before deciding whether to pursue design seriously.",
        "skill_gaps": ["Figma basics", "visual hierarchy", "color and typography", "case study presentation"],
        "known_skills": ["Canva", "Instagram content creation", "basic drawing", "Hindi writing"],
        "learning_style": "visual",
        "weekly_hours_available": 8,
        "device_access": "mobile",
        "language_preference": "hinglish",
        "confidence_level": "low",
        "urgency": "low",
        "motivation": "She enjoys creative work and wants a career path that feels more personal than preparing blindly for government exams.",
        "biggest_fear": "She fears choosing the wrong field and disappointing her family after spending time and money.",
        "icp_type": "low",
    },
    {
        "full_name": "Nikhil Raj",
        "age": 22,
        "location": "Patna",
        "education": "B.Tech in Civil Engineering",
        "current_role": "Fresher",
        "years_experience": 0,
        "current_salary_monthly": 0,
        "target_role": "Data Analyst Trainee",
        "target_salary_monthly": 28000,
        "primary_goal": "Switch from civil engineering job searches to data analyst trainee roles by learning Excel, SQL, and dashboard basics.",
        "skill_gaps": ["SQL joins", "Excel formulas", "data cleaning", "Power BI dashboards"],
        "known_skills": ["AutoCAD basics", "college mathematics", "presentation skills", "basic Excel"],
        "learning_style": "practice",
        "weekly_hours_available": 20,
        "device_access": "both",
        "language_preference": "hinglish",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He wants a faster career start because civil site jobs offered to him pay very little and require remote relocation.",
        "biggest_fear": "He fears being seen as a confused branch-switcher with no clear story for recruiters.",
        "icp_type": "low",
    },
    {
        "full_name": "Farheen Ansari",
        "age": 26,
        "location": "Bareilly",
        "education": "M.A. in Sociology",
        "current_role": "School Admin Assistant",
        "years_experience": 2,
        "current_salary_monthly": 14000,
        "target_role": "HR Operations Associate",
        "target_salary_monthly": 26000,
        "primary_goal": "Move into HR operations by learning HR tools, Excel reporting, employee data handling, and professional communication.",
        "skill_gaps": ["HRMS tools", "Excel reporting", "payroll basics", "formal workplace communication"],
        "known_skills": ["record keeping", "parent communication", "MS Word", "basic Excel", "document filing"],
        "learning_style": "video-first",
        "weekly_hours_available": 7,
        "device_access": "mobile",
        "language_preference": "hi",
        "confidence_level": "low",
        "urgency": "medium",
        "motivation": "She wants a respectable office career with better growth while staying close to her family.",
        "biggest_fear": "She fears her school admin work will not be valued by companies outside education.",
        "icp_type": "low",
    },
    {
        "full_name": "Vivek Tiwari",
        "age": 23,
        "location": "Jabalpur",
        "education": "B.Sc in Computer Science",
        "current_role": "Cyber Cafe Operator",
        "years_experience": 2,
        "current_salary_monthly": 12000,
        "target_role": "IT Helpdesk Technician",
        "target_salary_monthly": 30000,
        "primary_goal": "Get an IT helpdesk job by learning Windows troubleshooting, networking basics, hardware support, and ticketing workflows.",
        "skill_gaps": ["Windows administration", "LAN troubleshooting", "ticketing systems", "basic cybersecurity hygiene"],
        "known_skills": ["printer setup", "form filling", "basic hardware handling", "MS Office installation", "customer support"],
        "learning_style": "hands-on",
        "weekly_hours_available": 11,
        "device_access": "mobile",
        "language_preference": "hinglish",
        "confidence_level": "medium",
        "urgency": "high",
        "motivation": "He already solves small computer problems locally and wants to convert that experience into a formal IT role.",
        "biggest_fear": "He fears remaining in informal work where his skills are used daily but never recognized with a proper title.",
        "icp_type": "low",
    },
]


REQUIRED_FIELDS = {
    "full_name",
    "age",
    "location",
    "education",
    "current_role",
    "years_experience",
    "current_salary_monthly",
    "target_role",
    "target_salary_monthly",
    "primary_goal",
    "skill_gaps",
    "known_skills",
    "learning_style",
    "weekly_hours_available",
    "device_access",
    "language_preference",
    "confidence_level",
    "urgency",
    "motivation",
    "biggest_fear",
    "icp_type",
}


def validate_persona(persona: dict[str, Any]) -> None:
    missing = REQUIRED_FIELDS - persona.keys()
    if missing:
        raise ValueError(f"{persona.get('full_name', '<unknown>')} missing fields: {sorted(missing)}")

    allowed = {
        "learning_style": {"practice", "visual", "structured", "hands-on", "video-first"},
        "device_access": {"mobile", "laptop", "both"},
        "language_preference": {"en", "hi", "hinglish"},
        "confidence_level": {"low", "medium", "high"},
        "urgency": {"low", "medium", "high"},
        "icp_type": {"high", "low"},
    }
    for key, values in allowed.items():
        if persona[key] not in values:
            raise ValueError(f"{persona['full_name']} has invalid {key}: {persona[key]}")

    if not isinstance(persona["skill_gaps"], list) or not persona["skill_gaps"]:
        raise ValueError(f"{persona['full_name']} must have skill gaps")
    if not isinstance(persona["known_skills"], list) or not persona["known_skills"]:
        raise ValueError(f"{persona['full_name']} must have known skills")


def persona_with_user_id(persona: dict[str, Any], index: int) -> dict[str, Any]:
    enriched = {"user_id": f"user_{index:03d}"}
    enriched.update(persona)
    return enriched


def write_personas(output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    high_count = sum(1 for persona in PERSONAS if persona["icp_type"] == "high")
    low_count = sum(1 for persona in PERSONAS if persona["icp_type"] == "low")
    if len(PERSONAS) != 20 or high_count != 10 or low_count != 10:
        raise ValueError(f"Expected 20 personas split 10/10, got total={len(PERSONAS)} high={high_count} low={low_count}")

    written: list[Path] = []
    for idx, persona in enumerate(PERSONAS, start=1):
        validate_persona(persona)
        payload = persona_with_user_id(persona, idx)
        output_path = output_dir / f"user_{idx:03d}.json"
        output_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        written.append(output_path)

    return written


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Vidya V3 synthetic onboarding personas.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()

    written = write_personas(args.output_dir)
    print(f"Generated {len(written)} onboarding input files in {args.output_dir}")


if __name__ == "__main__":
    main()
